pipeline {
    agent any

    stages {
        stage('Checkout...') {
            steps {
               echo "Checkout code..."
            }
        }
        stage('Hello') {
            steps {
                sh "python section-08-deploying-with-containers/hello.py"
            }
        }
        
        stage ('TOX-Train model..'){
            steps{
                echo "Deploying to test env..."
                sh "tox -e train"
            }
        }
        stage ('Deploying to prod'){
            steps{
                echo "Deploying to prod env..."
            }
        }
    }
}
